// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(ReminderContext))]
    [Migration("20200726122758_InitModel")]
    partial class InitModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DAL.Model.Consentement", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Matricule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Consentements");
                });

            modelBuilder.Entity("DAL.Model.Echeance", b =>
                {
                    b.Property<string>("DossierNumero")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("EchappDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EchappDateTombEche")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EchappMontCapital")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EchappMontEch")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EchappMontTaxe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EchappNumero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EtcivAdressGeog1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EtcivMatricule")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EtcivNomreduit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EtcivNumcptContrib")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EtcivTelephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LibelleEngagement")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DossierNumero");

                    b.ToTable("Echeances");
                });

            modelBuilder.Entity("DAL.Model.Notification", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Canal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ConsentementID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateSend")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dossier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Echeance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ConsentementID");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("DAL.Model.Notification", b =>
                {
                    b.HasOne("DAL.Model.Consentement", "Consentement")
                        .WithMany("Notifications")
                        .HasForeignKey("ConsentementID");
                });
#pragma warning restore 612, 618
        }
    }
}
